### ISSUE TITLE
Still intressted to integrate network connection?

### ISSUE THREAD

**Issue by fabiankrauss** [rrooggiieerr/homeassistant-benqprojector#9]
Hey there @rrooggiieerr !

You mentioned in your readme that:
_"The same commands should work over a network connection, but I don't own such projector and have not implemented any network functionality. Contact me if you have a network connected BenQ projector and like this to work."_

I own a BenQ with LAN Connection and im totally intressted to integrated that with you togehter!

BR
Fabian

**Comment by rrooggiieerr** [comment]
That sounds great Fabian!

I'm not using my projector a lot at the moment because of summer time and not being at home a lot, but I'll try to help you where needed.

The conecction and commands are actually handled in the [benqprojector.py](https://github.com/rrooggiieerr/benqprojector.py) library, so thats where you should be to add the network connection.

Keep me posted on you progress and if you have any questions.

Rogier

**Comment by waazdakka** [comment]
Hello @rrooggiieerr!
I'm currently trying to connect my hass to my projector using lan. It has it's own IP address, and the only thing I could have get so far is this page when connecting from a web browser 😅
<img width="798" alt="Capture d’écran 2023-08-18 à 14 36 06" src="https://github.com/rrooggiieerr/homeassistant-benqprojector/assets/9380081/f6be6c93-d082-4011-a9ec-f70d0e4c03c7">

I'm not sure how to use your library to connect from Home Assistant, since the IP address is not an acceptable setting in your integration panel:
<img width="304" alt="Capture d’écran 2023-08-18 à 14 38 17" src="https://github.com/rrooggiieerr/homeassistant-benqprojector/assets/9380081/5b9e1ce2-e8a4-459d-a931-8c1da2b7894a">

How are we supposed to use it?

Thanks a lot!! (and sorry for the noob questions ^^')

**Comment by waazdakka** [comment]
Hello, I didn't tried anything more since my last post. But I'm still interested by the connection :)

**Comment by rrooggiieerr** [comment]
I actually implemented support for serial to networking bridges in the [benqprojector.py](https://github.com/rrooggiieerr/benqprojector.py) library. But having said that, it looks like your projector is using Creston RoomView Connect which seems to be a different protocol.

What model of BenQ projector are you using?

Can you try using the benqprojector.py library from the command line and connect to it?

**Comment by waazdakka** [comment]
I actually have a W4000i (the US reference is HT4550i).
I don't even know how Creston RoomView Connect works, but I'll try tonight from the command line! Thanks for your support!

**Comment by rrooggiieerr** [comment]
I just released a major update to the integration: network support. Still very much in beta since I don't own a networked projector. Let me know if it works for you.

**Comment by fabiankrauss** [comment]
Same here with the W5700

Am Do., 21. Dez. 2023 um 12:18 Uhr schrieb Dodoooh ***@***.***

**Comment by rrooggiieerr** [comment]
Thanks for giving it a try! Unfortunately without luck, yet.

My first questions would be:

Can you ping your projector from your HA instance?
Can you telnet to port 8000 of your projector?
If so, can you execute a command like
`*pow=?#`
And what response do you get

If not to port 8000, is there an other port available on your projector that accepts telnet connections? Maybe you could do a portscan on your projector to see which ports are available.

The integration does not use any web based interface to communicate with the projector, so if the only way to communicate with your projector is web based that's not going to work, it needs to be telnet and it needs to accept commands in the `*<key>=<value>#` format.

**Comment by rrooggiieerr** [comment]
@Dodoooh, for your W4000i I read in the [manual](https://esupportdownload.benq.com/esupport/PROJECTOR/UserManual/W4000i/W4000i_UM_EN_230517222352.pdf) that  there is support for "Control4", which I never heard off before but seems to be an other home automation platform. Maybe you can enable that and see if it makes a difference?

<img width="537" alt="Screenshot 2023-12-21 at 12 33 16" src="https://github.com/rrooggiieerr/homeassistant-benqprojector/assets/18603534/00211ca8-c329-47cb-bb32-5c3653e012b1">

**Comment by rrooggiieerr** [comment]
@fabiankrauss your W5700 seems to support a Network Standby Mode which disables the network connection after some time. Make sure it's disabled or try the integration with the projector turned on.

[W5700 manual for reference](https://esupportdownload.benq.com/esupport/PROJECTOR/UserManual/W5700/W5700_UM_EN_210203100126.pdf)

**Comment by fabiankrauss** [comment]
good hint :) the projector is on. May a other port?

Am Do., 21. Dez. 2023 um 12:40 Uhr schrieb rrooggiieerr <
***@***.***>:

**Comment by rrooggiieerr** [comment]
@fabiankrauss, yes, could be running on an other port too although the information I found online default port should be 8000. Maybe you need to enable something else in the menu. I didn't go trough the whole manual of your model, maybe you can have a good look in the manual and the menu options and see if there is something else that can be set.

Also, do a port scan of you projector over the full port range. and let me know which ports are open. Maybe that can give a hint.

**Comment by rrooggiieerr** [comment]
@Dodoooh Can you try telnet on the other ports? Just give an enter when connected and see if anything returns

**Comment by fabiankrauss** [comment]
looks like the same ports like @Dodoooh 

Discovered open port 8080/tcp
Discovered open port 80/tcp
Discovered open port 843/tcp
Discovered open port 41794/tcp
Discovered open port 8000/tcp
Discovered open port 4352/tcp
Discovered open port 1023/tcp
Discovered open port 55953/tcp
Discovered open port 55950/tcp

**Comment by rrooggiieerr** [comment]
Since I don't own a networked BenQ projector I think finding out how to make this work is not within reach for me. If you're able to find out how to make it work I'm more than happy to make the required changes to the library and integration.

The actual communication with the projector is done using the [benqprojector](https://github.com/rrooggiieerr/benqprojector.py) library. You could try to use that manually as described in the Readme and add the `-debug` argument to the `benqprojector` CLI command. Like so:
`python3 -m benqprojector telnet <host> <port> status --debug`

Maybe that gives some extra hints on what's going on

**Comment by fabiankrauss** [comment]
so what I can report:

PjLink on Port 4352 is working with putty and this class 1 comands: https://optics.fujifilm.com/projector/en/spec/manual/fp-z8000/technical_notes/pjlink/#pjlink_class1

but this is just basic.

**Comment by rrooggiieerr** [comment]
There is a PJLink integration for HA, but I don't think it's as extensive as my BenQ integration

https://www.home-assistant.io/integrations/pjlink/

**Comment by waazdakka** [comment]
Hello!
Sorry I wasn't able to run tests...

I found a way to access the flash interface of Crestron RoomView.
Here are the few settings we can found into this shinny interface!

<img width="799" alt="Capture d’écran 2024-02-10 à 22 19 55" src="https://github.com/rrooggiieerr/homeassistant-benqprojector/assets/9380081/32c9fbd7-1e0e-47fa-a802-308b2c2d63df">

I tried a lot of ports (80 / 843 / 1023 / 8000 / 8080 and finally 41794) without any success :(

**Comment by mrZeffka** [comment]
Any news on the topic?

**Comment by rrooggiieerr** [comment]
Network connection is implemented and should work, although I never got feedback of anyone using it

**Comment by mrZeffka** [comment]
I'm trying to connect Benq W5700, but it doesn't work.

**Comment by rrooggiieerr** [comment]
You need to give more details on what you're trying to do and what message you get. I don't own a networked projector myself so am totally dependent on proper feedback

**Comment by mrZeffka** [comment]
When adding a network address, the following error appears:
`Failed to connect`

Error in log:
`Registrar: benqprojector.benqprojector
Source: /usr/local/lib/python3.12/site-packages/benqprojector/benqprojector.py:277
First message: 17:58:40 (2 сообщений)
Last message: 17:59:58

Failed to get projector command prompt, is your projector properly connected?`

**Comment by rrooggiieerr** [comment]
Can you telnet to the port and what do you get then

**Comment by mrZeffka** [comment]
Telnet opens for me only on port 4352. But this is a PJLink port. (It also cannot connect through standard integration PJLink, although I can do everything through the test application)
No command can be executed. Everything is as described above in this thread.

**Comment by rrooggiieerr** [comment]
Then this integration does not work for you

**Comment by rrooggiieerr** [comment]
I learned some new things on how the network connection to the BenQ projectors work. I tried to implement that in the leatest library and integration. You might want to give that an other try

**Comment by waazdakka** [comment]
OK! I'll give a try this weekend! Thanks a lot

________________________________

**Comment by rrooggiieerr** [comment]
@Dodoooh, Bummer.

Have you followed these steps for settung up your projector?
<img width="713" alt="Screenshot 2024-07-15 at 22 16 19" src="https://github.com/user-attachments/assets/88146455-5425-47e6-af88-332e02b97d10">

There are a couple of things you could do, easiest first most difficult last:
Enable debug logging and do whatever you did when you got the "Unknown error occurred" message.
<img width="311" alt="Screenshot 2024-07-15 at 22 08 01" src="https://github.com/user-attachments/assets/e6fe479c-cb67-4c61-8897-2999ae88602d">
Then send me the resulting log file

You could try the CLI of the [BenQ projector library](https://github.com/rrooggiieerr/benqprojector.py) and enable debug there. Instructions are in the readme of the library but I'm also available to help you if you like to go that route.

Try a proper telnet client and connect to port 8000 of your projector and type in `<enter>*pow=?#<enter>`

If everything above fails you could temporary enable port forwarding port 8000 of your internet router to port 8000 of your projector and send me the external ip address of your internet connection and I could give it a try. However I would actually not recommend any of this because it definitely compromises your network security.

**Comment by rrooggiieerr** [comment]
> I can control the projector via telnet, also switch it off and on (standby activated)
Ok, so that means port 8000 is working.

You can also enable logging by adding these lines to your `configuration.yaml`:
```
logger:
  logs:
    custom_components.benqprojector: debug
    benqprojector: debug
```
And then restart HA.

The resulting log you can find in `home-assistant.log`

**Comment by rrooggiieerr** [comment]
> i realise that this does not always work in telnet. currently it does not want to work at all... i can always switch the projector off and on or change the source via telnet but "*pow=?#" doesn't want to give me anything at the moment.

Does it make a difference if the projector is on or off? That `*pow=?#` only works when the projector is on?

**Comment by rrooggiieerr** [comment]
That's quite interesting. So you're using a serial connection between your pc and projector and HA is using a networked connection? Does the projector echo the commands received on the network connection to the serial port? Thats a great way to debug.

Could you give the CLI of th [BenQ projector library](https://github.com/rrooggiieerr/benqprojector.py/) a try?

**Comment by waazdakka** [comment]
Hello @rrooggiieerr , I've finally managed to install my W4000i and connect it to the network, and it's perfectly recognized.
Network port used : 8000
<img width="671" alt="image" src="https://github.com/user-attachments/assets/cf76ae8c-335a-4f87-a2e2-00519adeb36b" />

The only problem is that... The projector is completely unreachable when turned off :( And I don't find any setting allowing wake on LAN ! Have to find another way to wake it but thanks for all the amazing work!!

**Comment by rrooggiieerr** [comment]
@waazdakka that's great to hear!

**Comment by mrZeffka** [comment]
I also finally managed to add my B5700 projector to the integration. This happened after I activated the permanent network mode and AMX control from the menu.

But now another problem has arisen: if the projector is turned on, the integration writes that the object is "Unavailable". If I turn off the projector, the device is detected again, but as soon as I turn it on, it becomes unavailable again.

I recorded a debug file. Could you please take a look at what could be the problem?
[home-assistant_benqprojector_2024-12-16T12-44-49.294Z.log](https://github.com/user-attachments/files/18150230/home-assistant_benqprojector_2024-12-16T12-44-49.294Z.log)
